# Vectors and Matrices in Python

## Import numpy as it is very useful for use to compute vectors and matrices in python

In [3]:
import numpy as np

## Create ket 0 and ket 1 (The standard basis vectors) using the numpy library

In [10]:
ket0 = np.array([[1], [0]])  # remember ket 0 is a column vector has 1 corrending to the outcome 0 and 0 to the outcome corresponding to 1
ket1 = np.array([[0], [1]])  # remember ket 1 is a column vector that has 0 corresponding to the outcome zero and 1 corresponding to the outcome 1

print(f"This is ket o {ket0}")
print(f"This is ket 1 {ket1}")

This is ket o [[1]
 [0]]
This is ket 1 [[0]
 [1]]


## Now perform a basic arrithmetic operation using ket 0 and ket 1

In [13]:
print(ket0/2 + ket1/2)

[[0.5]
 [0.5]]


## We can also use numpy to create matrices

In [16]:
M1 = np.array([[1,1], [0,0]])
M2 = np.array([[1,0], [0,1]])

print(M1)
print(M2)

[[1 1]
 [0 0]]
[[1 0]
 [0 1]]


## let's perform a basic operation using the matrices above

In [19]:
M = M1/2 + M2/2
print(M)

[[1.  0.5]
 [0.  0.5]]


## We can also perform matrix-vector multiplication using the matmul function in numpy

In [22]:
# using it for matrix-vector multiplication
print(np.matmul(M1, ket1))

# using it for matrix-matrix multiplication
print(np.matmul(M1, M2))

# using it to multiply a matrix with itself
print(np.matmul(M, M))

[[1]
 [0]]
[[1 1]
 [0 0]]
[[1.   0.75]
 [0.   0.25]]


## The output for the above operation, does not give the actual matrix look and feel. So we can use qiskit to get a better visualisation of the matrices

### using a method called array to latex in qiskit

In [28]:
# import the method from qiskit
from qiskit.visualization import array_to_latex

# display the results
display(array_to_latex(np.matmul(M1, ket1)))
display(array_to_latex(np.matmul(M1, M2)))
display(array_to_latex(np.matmul(M, M)))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>